// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZ8Fs29j_r6YRD31ffzBK2JsYpt1CL30',
    appId: '1:984898083629:web:0b7ac112023e5a598c91a4',
    messagingSenderId: '984898083629',
    projectId: 'caloridex',
    authDomain: 'caloridex.firebaseapp.com',
    storageBucket: 'caloridex.firebasestorage.app',
    measurementId: 'G-FFQ69VWH91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDwkHHKFP5oFJQ1xkP_yX63bSzI9lyMk',
    appId: '1:984898083629:android:5152df6f717ed8eb8c91a4',
    messagingSenderId: '984898083629',
    projectId: 'caloridex',
    storageBucket: 'caloridex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4XFrO3REXOYhng4OZOEf95FOKcKnykOw',
    appId: '1:984898083629:ios:b1f78a41b55fd04e8c91a4',
    messagingSenderId: '984898083629',
    projectId: 'caloridex',
    storageBucket: 'caloridex.firebasestorage.app',
    iosBundleId: 'com.example.caloridex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4XFrO3REXOYhng4OZOEf95FOKcKnykOw',
    appId: '1:984898083629:ios:b1f78a41b55fd04e8c91a4',
    messagingSenderId: '984898083629',
    projectId: 'caloridex',
    storageBucket: 'caloridex.firebasestorage.app',
    iosBundleId: 'com.example.caloridex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCZ8Fs29j_r6YRD31ffzBK2JsYpt1CL30',
    appId: '1:984898083629:web:4306ebaa4db288848c91a4',
    messagingSenderId: '984898083629',
    projectId: 'caloridex',
    authDomain: 'caloridex.firebaseapp.com',
    storageBucket: 'caloridex.firebasestorage.app',
    measurementId: 'G-S9M7RWVGWC',
  );
}
